// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Cep_iWSISy7Jjwt5K9nxaWpRXzwJLDI',
    appId: '1:1078138551100:web:132786a3ec8b07431b3c39',
    messagingSenderId: '1078138551100',
    projectId: 'queue-station',
    authDomain: 'queue-station.firebaseapp.com',
    storageBucket: 'queue-station.firebasestorage.app',
    measurementId: 'G-SM31LYFE49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5N7URIXVSqz27_BnhwYc8uI36qDuZchQ',
    appId: '1:1078138551100:android:503a7332d80b426f1b3c39',
    messagingSenderId: '1078138551100',
    projectId: 'queue-station',
    storageBucket: 'queue-station.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-aULKdyrUbo7dnr7k1es1V5H5zlIquIo',
    appId: '1:1078138551100:ios:48db44cbc069dc641b3c39',
    messagingSenderId: '1078138551100',
    projectId: 'queue-station',
    storageBucket: 'queue-station.firebasestorage.app',
    iosBundleId: 'com.example.queueStationApp',
  );
}
